import { useEffect, useState } from 'react';
import { Clock3, MapPin, Radio, RefreshCw } from 'lucide-react';
import { getShipments } from '../services/api.js';
import { getShipmentLocation } from '../services/location.js';

const FALLBACK_MAP_URL = 'https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d56774.78950966124!2d75.70623647701417!3d27.205823957312415!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1791124702929!5m2!1sen!2sin';
const freshness = (timestamp) => { if (!timestamp) return 'Location update unavailable'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(timestamp).getTime()) / 1000)); if (seconds < 5) return 'Last updated just now'; if (seconds < 60) return `Last updated ${seconds} seconds ago`; const minutes = Math.floor(seconds / 60); return `Last updated ${minutes} minute${minutes === 1 ? '' : 's'} ago`; };

export default function EmbeddedLocationMap() {
  const [shipments, setShipments] = useState([]); const [shipmentId, setShipmentId] = useState(''); const [location, setLocation] = useState(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  const shipment = shipments.find((item) => item.shipment_id === shipmentId); const mapKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY; const locationUrl = location && mapKey ? `https://www.google.com/maps/embed/v1/view?key=${encodeURIComponent(mapKey)}&center=${location.latitude},${location.longitude}&zoom=13` : FALLBACK_MAP_URL; const old = location?.updatedAt ? (Date.now() - new Date(location.updatedAt).getTime()) / 1000 > 120 : false;
  const load = async (id = shipmentId) => { if (!id) return; setLoading(true); try { const next = await getShipmentLocation(id); setLocation(next); setMessage(''); } catch { setLocation(null); setMessage('Location update unavailable'); } finally { setLoading(false); } };
  useEffect(() => { let active = true; getShipments().then((result) => { if (!active) return; const list = Array.isArray(result.shipments) ? result.shipments : []; setShipments(list); const preferred = list.find((item) => item.shipment_id === 'SHP001') || list[0]; setShipmentId(preferred?.shipment_id || ''); }).catch(() => setMessage('Unable to load shipment data.')); return () => { active = false; }; }, []);
  useEffect(() => { if (!shipmentId) return undefined; void load(shipmentId); const timer = window.setInterval(() => void load(shipmentId), 12000); return () => window.clearInterval(timer); }, [shipmentId]);
  const title = shipment ? `${shipment.shipment_id} · ${shipment.product_name}` : 'Selected shipment';
  return <section className="embedded-map-card live-map-card"><header><div><span className="embedded-map-kicker"><MapPin size={12} /> Live rider location</span><h2>Connected shipment tracking</h2></div><span className={`embedded-map-badge ${location && !old ? 'is-live' : 'is-muted'}`}><i /> {location && !old ? 'LIVE' : 'WAITING'}</span></header><div className="embedded-map-toolbar"><select value={shipmentId} onChange={(event) => setShipmentId(event.target.value)}><option value="">Choose shipment</option>{shipments.map((item) => <option key={item.shipment_id} value={item.shipment_id}>{item.shipment_id} · {item.product_name}</option>)}</select><button onClick={() => void load()} disabled={loading}>{loading ? <RefreshCw className="api-spin" size={14} /> : <Radio size={14} />} Refresh location</button></div><div className="embedded-map-stage"><iframe className="embedded-location-map" title={`Live rider location for ${title}`} src={locationUrl} allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin" /><div className="live-location-overlay"><strong><MapPin size={14} /> Current location</strong><b>{location && !old ? 'Rider is currently here' : old ? 'Location delayed' : 'Location data updating…'}</b><span>{title}</span><small>{location ? freshness(location.updatedAt) : 'Location update unavailable'}</small></div></div><div className="map-route-summary"><span>{(shipment?.origin || 'Origin').toUpperCase()}</span><b>→ &nbsp; Rider / connected device &nbsp; →</b><span>{(shipment?.destination || 'Destination').toUpperCase()}</span></div><div className="map-tracking-summary"><div><Radio size={15} /><small>Status</small><strong>{location && !old ? 'In transit' : 'Waiting'}</strong></div><div><MapPin size={15} /><small>Location</small><strong>{location && !old ? 'Tracking active' : 'Unavailable'}</strong></div><div><Clock3 size={15} /><small>Updated</small><strong>{location ? freshness(location.updatedAt).replace('Last updated ', '') : '—'}</strong></div></div><footer>{message || (location && old ? 'Location delayed — the tracking device may have lost connectivity.' : location ? 'Connected shipment tracking device' : 'Waiting for connected tracking device data.')}</footer></section>;
}
