import { useEffect, useRef, useState } from 'react';
import { CircleUserRound, LogOut, Mail, ShieldCheck, UserRound, X } from 'lucide-react';
import { getProfileRole, supabase } from '../services/supabase.js';

const initials = (name = '', email = '') => (name.trim() || email.split('@')[0] || 'User').split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase();

export default function ProfileMenu() {
  const [session, setSession] = useState(null); const [role, setRole] = useState('provider'); const [open, setOpen] = useState(false); const [modal, setModal] = useState(null); const menuRef = useRef(null);
  useEffect(() => { let active = true; const load = async () => { if (!supabase) return; const { data } = await supabase.auth.getSession(); if (!active || !data.session) return; setSession(data.session); setRole(await getProfileRole(data.session.user) || 'provider'); }; void load(); const listener = supabase ? supabase.auth.onAuthStateChange((_event, nextSession) => { if (active) { setSession(nextSession); setOpen(false); } }) : null; return () => { active = false; listener?.data?.subscription?.unsubscribe(); }; }, []);
  useEffect(() => { if (!open) return undefined; const close = (event) => { if (!menuRef.current?.contains(event.target)) setOpen(false); }; const escape = (event) => { if (event.key === 'Escape') { setOpen(false); setModal(null); } }; document.addEventListener('mousedown', close); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', escape); }; }, [open]);
  if (!session) return null;
  const user = session.user; const name = user.user_metadata?.full_name || user.user_metadata?.name || user.email?.split('@')[0] || 'ColdSense user'; const avatar = user.user_metadata?.avatar_url || user.user_metadata?.picture; const created = user.created_at ? new Date(user.created_at).toLocaleDateString() : 'Available'; const signOut = async () => { await supabase.auth.signOut(); setOpen(false); };
  return <div className="profile-menu-wrap" ref={menuRef}><button className="profile-trigger" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Open account menu">{avatar ? <img src={avatar} alt="" /> : <span>{initials(name, user.email)}</span>}</button>{open && <div className="profile-popover"><div className="profile-summary">{avatar ? <img src={avatar} alt="" /> : <span>{initials(name, user.email)}</span>}<div><strong>{name}</strong><small>{user.email}</small><b>{role.toUpperCase()}</b></div></div><div className="profile-actions"><button onClick={() => { setModal('profile'); setOpen(false); }}><UserRound size={15} /> Profile</button><button onClick={() => { setModal('account'); setOpen(false); }}><ShieldCheck size={15} /> Account</button></div><button className="profile-logout" onClick={() => void signOut()}><LogOut size={15} /> Log out</button></div>}{modal && <div className="profile-modal-backdrop" onMouseDown={() => setModal(null)}><section className="profile-modal" onMouseDown={(event) => event.stopPropagation()}><button className="profile-modal-close" onClick={() => setModal(null)}><X size={16} /></button><span className="auth-kicker">{modal === 'profile' ? 'Profile' : 'Account'}</span><h2>{modal === 'profile' ? name : 'Account details'}</h2>{modal === 'profile' ? <><p><Mail size={14} /> {user.email}</p><p><ShieldCheck size={14} /> Role: <b>{role.toUpperCase()}</b></p><p><CircleUserRound size={14} /> Account created: {created}</p></> : <><p><Mail size={14} /> {user.email}</p><p><ShieldCheck size={14} /> Authentication: Supabase</p><p><CircleUserRound size={14} /> Session: Active</p><p><b>Role:</b> {role === 'rider' ? 'Rider' : 'Provider'}</p></>}<small className="profile-note">Role changes require signing out and authenticating with the appropriate account.</small></section></div>}</div>;
}
